### ISSUE TITLE
Dynamic fonts missing characters under WebGL

### ISSUE THREAD

**Issue by Elringus** [Naninovel/Documentation#118]
When using an uGUI with a dynamic font, at some point random characters could stop rendering properly when running a WebGL build.

The issue is caused by Unity's text engine failing to resize font atlases under WebGL.

For a workaround, either use TMPro text or switch to non-dynamic fonts, eg:

![](https://i.gyazo.com/db69d46adba0832468695dc2659dc22e.png)

**Comment by Elringus** [comment]
Doesn't seem to reproduce on Unity 2019.4.22 and later. If someone happen to reproduce this with a recent Unity release, please contact the support.

**Comment by MehmetDinc-crypto** [comment]
I've got same problem in Unity2020.3.23f1.

**Comment by Develeone** [comment]
Reproduced at 2021.2.8f1 (MacOS Editor, WebGL build)
But I'm too lazy to make a bug report, just keeping you posted.

**Comment by Elringus** [comment]
> Reproduced at 2021.2.8f1 (MacOS Editor, WebGL build)
Well, they've either broke it again or didn't fix on MacOS specifically (our WebGL demo is working fine on Windows with Unity 2019.4.25). In either case, please contact Unity support if you'd like to report the issue.

**Comment by manundi** [comment]
Is there a way to use dynamic fonts with emojis in webgl?

**Comment by elringus** [comment]
> Is there a way to use dynamic fonts with emojis in webgl?

Naninovel no longer uses Unity's legacy text component. TMPro is the default solution and does support emojis on all platforms.
