### ISSUE TITLE
Error on entering play mode in Unity 2019.4.14 and later

### ISSUE THREAD

**Issue by Elringus** [Naninovel/Documentation#127]
After restarting Unity editor, an `UnobservedTaskException` exception is raised. 

This is caused by a regression (bug) introduced in Unity versions 2019.4.14f1 and later. 

As a temporary workaround, when the error occurs, right-click "Naninovel" folder and click "Reimport". 
Alternatively, downgrade to Unity 2019.4.13f1.

Update: The issue is acknowledged by Unity. 
**Please vote to make it fixed as soon as possible**: https://issuetracker.unity3d.com/product/unity/issues/guid/1296212

**Comment by JackStandard** [comment]
I've been hit by this issue and your temporary workaround worked for me. Thank you so much for posting this.

**Comment by Elringus** [comment]
Fixed in Unity 2019.4.22f1
