### ISSUE TITLE
Failed to install IDE extension on Apple Silicon (M1) devices

### ISSUE THREAD

**Issue by Elringus** [Naninovel/Documentation#133]
Caused by Microsoft not supporting mac arm architecture on .NET 3.1 or .NET 5.

Use Rosetta 2 emulation until we migrate the IDE extension to .NET 6.

Associated issue: https://github.com/dotnet/vscode-dotnet-runtime/issues/201

**Comment by shar0** [comment]
I got same problems too, just move to M1 in this week 😭

**Comment by Elringus** [comment]
I'm not entirely sure, but judging by https://github.com/dotnet/runtime/issues/43313 Microsoft won't be supporting arm-based mac devices on .NET 3.1 or .NET 5 and are recommending using Rosetta 2 emulation for such cases, while native support is planned for .NET 6 (which is currently in preview). We'll probably move the IDE extension to .NET 6 at some point, but until that arm mac users will probably have to use the emulators.

**Comment by Elringus** [comment]
Should be resolved with extension v1.6.0, as it's now built with .NET 6.
