### ISSUE TITLE
Extra white space in visual script editor on Unity 2021.2

### ISSUE THREAD

**Issue by Elringus** [Naninovel/Documentation#144]
Caused by a bug in Unity's "2D Animation" package (added by default in new project created from 2D template): https://issuetracker.unity3d.com/product/unity/issues/guid/1345049

Please vote on the tracker to make it fixed as soon as possible.

**Comment by J0xFlash** [comment]
Voted

**Comment by Elringus** [comment]
Fixed in Naninovel v1.17.
