### ISSUE TITLE
Syntax highlighting and suggestions doesn't work in vs code

### ISSUE THREAD

**Issue by ilr00743** [naninovel/Documentation#161]
![image](https://github.com/naninovel/Documentation/assets/28483189/c527e9a7-127b-4f13-a5f7-317774256878)
![image](https://github.com/naninovel/Documentation/assets/28483189/e93f5f07-a640-42ee-812f-0876f92559dd)

**Comment by elringus** [comment]
Hi, Please contact the support: https://naninovel.com/support/#naninovel-support
